// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2439.SH16Bot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc2439.SH16Bot.subsystems.*;

/**
 *  An Autonomous Command for breaching the 'simple' defenses,
 *  (i.e., Rock Wall, Rough Terrain, Moat, Ramparts.
 *  
 *  Match Setup::
 *  	1) Intake Arm in raised position.
 *  	2) Ball inserted in intake for later teleop scoring.
 * 		3) Robot with rear wheel axle centered on line.
 * 		4a) Intake arm centered on middle raised ramp.
 * 		5a) Robot aligned straight (perpendicular to defense).
 * 		4b) For Ramparts, align robot so that one front wheel 
 * 		    hits the raised side at an angle (as practiced).
 * 
 * 	Command Sequence:
 * 		-  Robot simply drives straight over defense and into
 * 		   courtyard.
 *
 */
public class AutoSimpleBreachCmd extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutoSimpleBreachCmd() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    	addSequential(new ShiftDownCmd());
        addSequential(new DriveStraightCmd(0.8,6000.));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
    } 
}
