// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2439.SH16Bot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2439.SH16Bot.Robot;
import org.usfirst.frc2439.SH16Bot.RobotMap;
import edu.wpi.first.wpilibj.smartdashboard.*;

/**
 *
 */
public class MoveIntakeCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public MoveIntakeCmd() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.ballIntake);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	//Robot.ballIntake.raise();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	RobotMap.ballIntakeRightArmMotor.set( Robot.oi.getLeftJS().getY()/2.0 );
    	RobotMap.ballIntakeLeftArmMotor.set( -Robot.oi.getLeftJS().getY()/2.0 );

    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        //return Robot.ballIntake.getPIDController().onTarget();
    	if( !Robot.oi.manualIntakeArmBtn.get() )
		{
    		RobotMap.ballIntakeRightArmMotor.set(0);
    		RobotMap.ballIntakeLeftArmMotor.set(0);

    		return true;
		}
		else return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	RobotMap.ballIntakeRightArmMotor.set(0);
    	RobotMap.ballIntakeLeftArmMotor.set(0);

    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
