// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2439.SH16Bot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc2439.SH16Bot.subsystems.*;

/**
 */
public class RetractCopleyArmCmd extends CommandGroup {

	private final int EXTEND=0;
	private final int RETRACT=1;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public RetractCopleyArmCmd() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        addSequential(new ControlSallyUpperArmCmd(RETRACT));
        addSequential(new ControlSallyLowerArmCmd(RETRACT));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
    } 
}
